// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package pkg

import (
	"GoSOLID/pkg/drivers"
	"GoSOLID/pkg/services/repositories"
)

// Injectors from wire.go:

func InitializeJsonListRepository() *repositories.JsonListRepository {
	string2 := _wireStringValue
	jsonDriver := drivers.NewJsonDriver(string2)
	jsonListRepository := repositories.NewJsonListRepository(jsonDriver)
	return jsonListRepository
}

var (
	_wireStringValue = "../data/list.json"
)

func InitializeSqliteListRepository() *repositories.SqliteListRepository {
	sqliteListRepository := repositories.NewSqliteListRepository()
	return sqliteListRepository
}

func InitializeListRepository() repositories.ListRepository {
	sqliteListRepository := repositories.NewSqliteListRepository()
	return sqliteListRepository
}
